services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=sualasoft_db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-net

  web:
    image: odoo:19
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=password
      - DB_NAME=sualasoft_db
    volumes:
      - odoo_data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    networks:
      - odoo-net

volumes:
  db_data:
  odoo_data:

networks:
  odoo-net:
    driver: bridge
